<Project>

  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <!-- Release -->
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <!-- Debug -->
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
  </PropertyGroup>

</Project>