<Project Sdk="ricaun.Revit.Sdk/0.12.0-alpha.1000">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <TargetFrameworks>TargetFrameworksReplace</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="RevitTest.cs" />
    <None Include="Utils\OneTimeOpenDocumentTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="ricaun.RevitTest.TestAdapter" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" Condition="!$(TargetFramework.StartsWith('net4'))" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion).*-*" IncludeAssets="build; compile" PrivateAssets="All" />
  </ItemGroup>

  <!-- Release -->
  <ItemGroup Condition="!$(Configuration.Contains('Debug'))">
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Open</_Parameter1>
      <_Parameter2>true</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Close</_Parameter1>
      <_Parameter2>true</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
